action = { SOI ~ (function_def | query | command) ~ EOI }

function_def = { ID ~ "(" ~ ID? ~ ")" ~ ":=" ~ expr }
query = { expr }
command = { show_code_command }
show_code_command = { ".code" ~ ID }

expr = { addsub }

addsub = { muldiv ~ (addsub_op ~ addsub)?  }
addsub_op = { "+" | "-" }
muldiv = { atom ~ (muldiv_op ~ muldiv)? }
muldiv_op = { "*" | "/" }
atom = {
    "(" ~ expr ~ ")" |
    NUMBER |
    ID
}

ID = { ASCII_ALPHA+ }
NUMBER = { ASCII_DIGIT+ }
WHITESPACE = _{ " " }